title: preqon 

description: "Neuroscience and computer science graduate from the University of 
Sydney. Seeking opportunities in brain-computer interfaces." 

url: "https://preqon.github.io" # the base hostname & protocol for your site, e.g. http://example.com

baseurl: "" # the subpath of your site, e.g. /blog
