theme: academic-jekyll-theme

title: preqon 

description: This website contains my portfolio of work inside neuroscience, artificial intelligence and neurotechnology. 

url: "https://preqon.github.io" # the base hostname & protocol for your site, e.g. http://example.com

baseurl: "" # the subpath of your site, e.g. /blog
