title: preqon 

description: "Neuroscience and computer science graduate from the University of 
Sydney. Studies all things intelligent." 

url: "https://preqon.github.io" # the base hostname & protocol for your site, e.g. http://example.com

baseurl: "" # the subpath of your site, e.g. /blog
