title: preqon 

description: "Neuroscience and computer science graduate from the University of 
Sydney. Seeking opportunities in R&D teams in neurotechnology." 

url: "https://preqon.github.io" # the base hostname & protocol for your site, e.g. http://example.com

baseurl: "" # the subpath of your site, e.g. /blog

sass:
  sass_dir: _sass 
  style: compressed # compressed or expanded 
