menu:
- {name: 'about', url: '/'}
- {name: 'projects', url: '/projects'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

projects:
- {name: 'Information transfer in mouse brains (honours project)', url: 'honours'}
- {name: 'Spiking neural network for detecting speech emotion', url: 'speech-emotion-snn'}

social:
- {icon: 'github', link: 'https://github.com/preqon'}
- {icon: 'twitter', link: 'https://twitter.com/preqon1'}

contacts:
- {name: 'Preethom Pal', 
email: 'pal.pree@gmail.com',
twitter: '@preqon1',
github: 'preqon',
image: 'assets/img/contact.jpg'}
