menu:
- {name: 'projects', url: '/projects'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

projects:
- {name: 'Information transfer in mouse brains (honours project)', url: 'honours'}

social:
- {icon: 'github', link: 'https://github.com/preqon'}
- {icon: 'twitter', link: 'https://twitter.com/preqon1'}

contacts:
- {name: 'Preethom Pal', title: 'Graduate', department: 'School of Computer Science', institution: 'University of Sydney', institution_address: 'Camperdown, NSW', email: 'contact@preqon.xyz', image: 'assets/img/contact.png'}
