menu:
- {name: 'about', url: '/'}
- {name: 'projects', url: '/projects'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

projects:
- {name: 'Information transfer in mouse brains (honours project)',
url: 'honours'}
- {name: 'Spiking neural network for detecting speech emotion (incomplete)',
url: 'speech-emotion-snn'}
- {name: 'PHYS4015 course notes', url: 'phys4015' }
- {name: 'COMP5328 course notes', url: 'comp5328' }

social:
- {icon: 'github', link: 'https://github.com/preqon'}
- {icon: 'twitter', link: 'https://twitter.com/preqon1'}

contacts:
- {name: 'Preethom Pal', 
twitter: '@preqon1',
image: 'assets/img/contact.jpg'}
